name: Build [All]

on:
  workflow_dispatch:
  push:
    paths:
      - 'installer/*'
      - 'installer_res/*'
      - '.github/workflows/compile-core.yml'
  pull_request:
  schedule:
    - cron: "0 15 * * 5"
#  repository_dispatch:
#    types: [Component_update]
    
    
jobs:
  build-packages:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip p7zip

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch

    - name: Get short SHA
      id: slug
      run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Compile
      run: |
        cd installer
        make rebuild FMCB_INSTALLER_VERSION=${{ env.SHA8 }} EE_BIN_DIR=../installer_res/ 
        make rebuild FMCB_INSTALLER_VERSION=${{ env.SHA8 }} EE_BIN_DIR=../installer_res/ EXFAT=1

    - name: Prepare folder for Release
      run: |
        cd installer_res
        ls
        chmod +x ./pack.sh
        ./pack.sh

    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: FMCB-${{ env.SHA8 }}
        path: |
            FMCBInst*.7z

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "FreeMcBoot"
        files: |
            FMCB*.7z
